on:
  tags: true

sudo: required

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"

script:
  - docker build -t "vifino/torch:${TRAVIS_TAG:-latest}" -f Dockerfile .

after_success:
  - docker push vifino/torch
